routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/', App\Http\Controllers\FrontController::class)->name('front');

Auth::routes();

Route::apiResource('attachments', \App\Http\Controllers\AttachmentController::class)->only(['store', 'show', 'destroy']);

Route::group([ 'prefix' => 'admin', 'middleware' => 'auth' ], function() {

    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('admin');
    
    
    Route::resource('generalSettings', App\Http\Controllers\GeneralSettingController::class);
    
    
    Route::resource('myExpertises', App\Http\Controllers\MyExpertiseController::class);
    
    
    Route::resource('myExperiences', App\Http\Controllers\MyExperienceController::class);
    
    
    Route::resource('education', App\Http\Controllers\EducationController::class);
    
    
    Route::resource('skills', App\Http\Controllers\SkillController::class);
});




Route::resource('testimonials', App\Http\Controllers\TestimonialController::class);


Route::resource('portfolios', App\Http\Controllers\PortfolioController::class);

resources/views/my_expertises/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create My Expertise</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'myExpertises.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('my_expertises.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('myExpertises.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/my_expertises/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit My Expertise</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($myExpertise, ['route' => ['myExpertises.update', $myExpertise->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('my_expertises.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('myExpertises.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/my_expertises/fields.blade.php
<div class="col-md-12">
    <div class="form-group">
        {!! Form::label('name', 'Name*') !!}
        {!! Form::text(
        'name',
        null,
        [
        'class' => 'form-control ' . ($errors->has('name') ? 'is-invalid' : ''),
        'maxlength' => '100',
        'minlength' => '3',
        'required'
        ]
        ) !!}
        @error('name')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>
    <div class="form-group">
        {!! Form::label('caption', 'Caption*') !!}
        {!! Form::textarea(
        'caption',
        null,
        [
        'class' => 'form-control ' . ($errors->has('caption') ? 'is-invalid' : ''),
        'maxlength' => '255',
        'minlength' => '3',
        'required'
        ]
        ) !!}
        @error('caption')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>
    <div class="form-group">
        {!! Form::label('icon_name', 'Icon Name*') !!}
        {!! Form::text(
        'icon_name',
        null,
        [
        'class' => 'form-control ' . ($errors->has('icon_name') ? 'is-invalid' : ''),
        'maxlength' => '50',
        'minlength' => '3',
        'required'
        ]
        ) !!}
        @error('icon_name')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>
</div>

resources/views/my_expertises/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>My Expertises</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('myExpertises.create') }}">
                        Add New
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('my_expertises.table')

                <div class="card-footer clearfix">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/my_expertises/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>My Expertise Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('myExpertises.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('my_expertises.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/my_expertises/show_fields.blade.php
<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $myExpertise->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $myExpertise->updated_at }}</p>
</div>

resources/views/my_expertises/table.blade.php
<div class="table-responsive">
    <table class="table" id="myExpertises-table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Caption</th>
                <th>Icon</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach($myExpertises as $myExpertise)
            <tr>
                <td>{{ $myExpertise->name }}</td>
                <td>{{ $myExpertise->caption }}</td>
                <td><i class="fas fa-{{$myExpertise->icon_name}}"></i></td>
                <td width="120">
                    {!! Form::open(['route' => ['myExpertises.destroy', $myExpertise->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('myExpertises.show', [$myExpertise->id]) }}" class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('myExpertises.edit', [$myExpertise->id]) }}" class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn
                        btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>