routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/', App\Http\Controllers\FrontController::class)->name('front');

Auth::routes();

Route::apiResource('attachments', \App\Http\Controllers\AttachmentController::class)->only(['store', 'show', 'destroy']);

Route::group([ 'prefix' => 'admin', 'middleware' => 'auth' ], function() {

    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('admin');
    
    
    Route::resource('generalSettings', App\Http\Controllers\GeneralSettingController::class);
    
    
    Route::resource('myExpertises', App\Http\Controllers\MyExpertiseController::class);
    
    
    Route::resource('myExperiences', App\Http\Controllers\MyExperienceController::class);
    
    
    Route::resource('education', App\Http\Controllers\EducationController::class);
    
    
    Route::resource('skills', App\Http\Controllers\SkillController::class);
});




Route::resource('testimonials', App\Http\Controllers\TestimonialController::class);


Route::resource('portfolios', App\Http\Controllers\PortfolioController::class);

app/Models/GeneralSetting.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class GeneralSetting
 * @package App\Models
 * @version August 5, 2022, 1:15 am UTC
 *
 */
class GeneralSetting extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'general_settings';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'name',
        'email',
        'phone',
        'headquarter',
        'about_me',
        'linkedin_url',
        'facebook_url',
        'instagram_url',
        'youtube_url',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
      'name'    => 'required|string|min:3',
      'email'   => 'required|string|min:3',
      'phone'   => 'required|string',
    ];

    public function firstFrontBanner()
    {
        return $this->morphOne(Attachment::class, 'attachable')
            ->fileAttachment('first_front_banner');
    }

    public function secondFrontBanner()
    {
        return $this->morphOne(Attachment::class, 'attachable')
            ->fileAttachment('second_front_banner');
    }

    public function cvDocument()
    {
        return $this->morphOne(Attachment::class, 'attachable')
            ->fileAttachment('cv_document');
    }

    public function portfolioDocument()
    {
        return $this->morphOne(Attachment::class, 'attachable')
            ->fileAttachment('portfolio_document');
    }
    
}

app/Http/Controllers/GeneralSettingController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateGeneralSettingRequest;
use App\Http\Requests\UpdateGeneralSettingRequest;
use App\Repositories\GeneralSettingRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class GeneralSettingController extends AppBaseController
{
    /** @var GeneralSettingRepository $generalSettingRepository*/
    private $generalSettingRepository;

    public function __construct(GeneralSettingRepository $generalSettingRepo)
    {
        $this->generalSettingRepository = $generalSettingRepo;
    }

    /**
     * Display a listing of the GeneralSetting.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $generalSettings = $this->generalSettingRepository->all();

        return view('general_settings.index')
            ->with('generalSettings', $generalSettings);
    }

    /**
     * Show the form for creating a new GeneralSetting.
     *
     * @return Response
     */
    public function create()
    {
        return view('general_settings.create');
    }

    /**
     * Store a newly created GeneralSetting in storage.
     *
     * @param CreateGeneralSettingRequest $request
     *
     * @return Response
     */
    public function store(CreateGeneralSettingRequest $request)
    {
        $input = $request->all();

        $generalSetting = $this->generalSettingRepository->create($input);

        Flash::success('General Setting saved successfully.');

        return redirect(route('generalSettings.index'));
    }

    /**
     * Display the specified GeneralSetting.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $generalSetting = $this->generalSettingRepository->find($id);

        if (empty($generalSetting)) {
            Flash::error('General Setting not found');

            return redirect(route('generalSettings.index'));
        }

        return view('general_settings.show')->with('generalSetting', $generalSetting);
    }

    /**
     * Show the form for editing the specified GeneralSetting.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $generalSetting = $this->generalSettingRepository->find($id);

        if (empty($generalSetting)) {
            Flash::error('General Setting not found');

            return redirect(route('generalSettings.index'));
        }

        return view('general_settings.edit')->with('generalSetting', $generalSetting);
    }

    /**
     * Update the specified GeneralSetting in storage.
     *
     * @param int $id
     * @param UpdateGeneralSettingRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateGeneralSettingRequest $request)
    {
        $generalSetting = $this->generalSettingRepository->find($id);

        if (empty($generalSetting)) {
            Flash::error('General Setting not found');

            return redirect(route('generalSettings.index'));
        }

        $generalSetting = $this->generalSettingRepository->update($request->all(), $id);

        Flash::success('General Setting updated successfully.');

        return redirect(route('generalSettings.index'));
    }

    /**
     * Remove the specified GeneralSetting from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $generalSetting = $this->generalSettingRepository->find($id);

        if (empty($generalSetting)) {
            Flash::error('General Setting not found');

            return redirect(route('generalSettings.index'));
        }

        $this->generalSettingRepository->delete($id);

        Flash::success('General Setting deleted successfully.');

        return redirect(route('generalSettings.index'));
    }
}

resources/views/general_settings/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create General Setting</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'generalSettings.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('general_settings.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('generalSettings.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/general_settings/cv_document.blade.php
@component('components.uploader', [
'name' => 'cv_document',
'label' => 'CV',
'removeable' => true,
'extensions' => '.pdf',
'attachments' => isset($generalSetting) ? ($generalSetting->cvDocument()->exists() ?
[$generalSetting->cvDocument] : []) :
[],
'attachable_type' => 'general_setting',
'attachable_id' => isset($generalSetting) ? $generalSetting->id : '',
'file_attachment' => 'cv_document'
])
Ekstensi diperbolehkan (pdf).
Menerima 1 berkas.
Maks. ukuran berkas 2MB
@endcomponent

resources/views/general_settings/edit.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <h1>Edit General Setting</h1>
            </div>
        </div>
    </div>
</section>

<div class="content px-3">

    @include('adminlte-templates::common.errors')

    <div class="card">

        {!! Form::model($generalSetting, ['route' => ['generalSettings.update', $generalSetting->id], 'method' =>
        'patch']) !!}

        <div class="card-body">
            <div class="row">
                @include('general_settings.fields')
            </div>
        </div>

        <div class="card-footer">
            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
            <a href="{{ route('generalSettings.index') }}" class="btn btn-default">Cancel</a>
        </div>

        {!! Form::close() !!}

    </div>
</div>
@endsection

resources/views/general_settings/fields.blade.php
<div class="col-md-12">
    <div class="form-group">
        {!! Form::label('name', 'Name*') !!}
        {!! Form::text(
        'name',
        null,
        [
        'class' => 'form-control ' . ($errors->has('name') ? 'is-invalid' : ''),
        'maxlength' => '50',
        'minlength' => '3',
        'required'
        ]
        ) !!}
        @error('name')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>

    <div class="form-group">
        {!! Form::label('email', 'Email*') !!}
        {!! Form::text(
        'email',
        null,
        [
        'class' => 'form-control ' . ($errors->has('email') ? 'is-invalid' : ''),
        'maxlength' => '50',
        'minlength' => '3',
        'required'
        ]
        ) !!}
        @error('email')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>

    <div class="form-group">
        {!! Form::label('phone', 'Phone*') !!}
        {!! Form::text(
        'phone',
        null,
        [
        'class' => 'form-control ' . ($errors->has('phone') ? 'is-invalid' : ''),
        'maxlength' => '20',
        'required'
        ]
        ) !!}
        @error('phone')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>

    <div class="form-group">
        {!! Form::label('headquarter', 'Headquarter*') !!}
        {!! Form::text(
        'headquarter',
        null,
        [
        'class' => 'form-control ' . ($errors->has('headquarter') ? 'is-invalid' : ''),
        'maxlength' => '20',
        'required'
        ]
        ) !!}
        @error('headquarter')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>

    <div class="form-group">
        {!! Form::label('about_me', 'About Me*') !!}
        {!! Form::textarea(
        'about_me',
        null,
        [
        'class' => 'form-control ' . ($errors->has('about_me') ? 'is-invalid' : ''),
        'maxlength' => '20',
        'required'
        ]
        ) !!}
        @error('about_me')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>

    <div class="form-group">
        {!! Form::label('linkedin_url', 'LinkedIn') !!}
        {!! Form::text(
        'linkedin_url',
        null,
        [
        'class' => 'form-control ' . ($errors->has('linkedin_url') ? 'is-invalid' : ''),
        'maxlength' => '20',
        'required'
        ]
        ) !!}
        @error('linkedin_url')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>

    <div class="form-group">
        {!! Form::label('facebook_url', 'Facebook') !!}
        {!! Form::text(
        'facebook_url',
        null,
        [
        'class' => 'form-control ' . ($errors->has('facebook_url') ? 'is-invalid' : ''),
        'maxlength' => '20',
        'required'
        ]
        ) !!}
        @error('facebook_url')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>

    <div class="form-group">
        {!! Form::label('instagram_url', 'Instagram') !!}
        {!! Form::text(
        'instagram_url',
        null,
        [
        'class' => 'form-control ' . ($errors->has('instagram_url') ? 'is-invalid' : ''),
        'maxlength' => '20',
        'required'
        ]
        ) !!}
        @error('instagram_url')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>

    @include('general_settings.image')
    @include('general_settings.second_banner')
    @include('general_settings.cv_document')
    @include('general_settings.portfolio_document')
</div>

resources/views/general_settings/image.blade.php
@component('components.uploader', [
'name' => 'front_banner',
'label' => 'Banner Pertama',
'removeable' => true,
'extensions' => '.jpg,.png.jpeg',
'attachments' => isset($generalSetting) ? ($generalSetting->firstFrontBanner()->exists() ?
[$generalSetting->firstFrontBanner] : []) :
[],
'attachable_type' => 'general_setting',
'attachable_id' => isset($generalSetting) ? $generalSetting->id : '',
'file_attachment' => 'first_front_banner'
])
Ekstensi diperbolehkan (png)
Menerima 1 berkas
Maks. ukuran berkas 2MB
@endcomponent

resources/views/general_settings/index.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>General Settings</h1>
            </div>
            {{-- <div class="col-sm-6">
                <a class="btn btn-primary float-right" href="{{ route('generalSettings.create') }}">
                    Add New
                </a>
            </div> --}}
        </div>
    </div>
</section>

<div class="content px-3">

    @include('flash::message')

    <div class="clearfix"></div>

    <div class="card">
        <div class="card-body p-0">
            @include('general_settings.table')

            <div class="card-footer clearfix">
                <div class="float-right">

                </div>
            </div>
        </div>

    </div>
</div>

@endsection

resources/views/general_settings/portfolio_document.blade.php
@component('components.uploader', [
'name' => 'portfolio_document',
'label' => 'Portfolio',
'removeable' => true,
'extensions' => '.pdf,.docx',
'attachments' => isset($generalSetting) ? ($generalSetting->portfolioDocument()->exists() ?
[$generalSetting->portfolioDocument] : []) :
[],
'attachable_type' => 'general_setting',
'attachable_id' => isset($generalSetting) ? $generalSetting->id : '',
'file_attachment' => 'portfolio_document'
])
Ekstensi diperbolehkan (pdf).
Menerima 1 berkas.
Maks. ukuran berkas 4MB
@endcomponent

resources/views/general_settings/second_banner.blade.php
@component('components.uploader', [
'name' => 'second_front_banner',
'label' => 'Banner Kedua',
'removeable' => true,
'extensions' => '.jpg,.png.jpeg',
'attachments' => isset($generalSetting) ? ($generalSetting->secondFrontBanner()->exists() ?
[$generalSetting->secondFrontBanner] : []) :
[],
'attachable_type' => 'general_setting',
'attachable_id' => isset($generalSetting) ? $generalSetting->id : '',
'file_attachment' => 'second_front_banner'
])
Ekstensi diperbolehkan (png)
Menerima 1 berkas
Maks. ukuran berkas 2MB
@endcomponent

resources/views/general_settings/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>General Setting Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('generalSettings.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('general_settings.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/general_settings/show_fields.blade.php
<div class="col-md-6">
    {!! Form::label('name', 'Name:') !!}
    <p>{{ $generalSetting->name }}</p>
</div>

<div class="col-md-6">
    {!! Form::label('email', 'Email:') !!}
    <p>{{ $generalSetting->email }}</p>
</div>

<div class="col-md-6">
    {!! Form::label('phone', 'Phone:') !!}
    <p>{{ $generalSetting->phone }}</p>
</div>

<!-- Created At Field -->
<div class="col-sm-6">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $generalSetting->created_at }}</p>
</div>

<div class="col-md-6">
    {!! Form::label('facebook_url', 'Facebook:') !!}
    <p>{{ $generalSetting->facebook_url }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-6">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $generalSetting->updated_at }}</p>
</div>

<div class="col-md-6">
    {!! Form::label('linkedin_url', 'LinkedIn:') !!}
    <p>{{ $generalSetting->linkedin_url }}</p>
</div>

<div class="col-md-6">
    {!! Form::label('instagram_url', 'Instagram:') !!}
    <p>{{ $generalSetting->instagram_url }}</p>
</div>

<div class="col-md-6">
    {!! Form::label('youtube_url', 'Youtube:') !!}
    <p>{{ $generalSetting->youtube_url }}</p>
</div>

resources/views/general_settings/table.blade.php
<div class="table-responsive">
    <table class="table" id="generalSettings-table">
        <thead>
            <tr>

                <th>Name</th>
                <th>E-mail</th>
                <th>Phone</th>
                <th>Headquarter</th>
                <th>LinkedIn</th>
                <th>Facebook</th>
                <th>Instagram</th>
                <th>Youtube</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach($generalSettings as $generalSetting)
            <tr>
                <td>{{ $generalSetting->name }}</td>
                <td>{{ $generalSetting->email }}</td>
                <td>{{ $generalSetting->phone }}</td>
                <td>{{ $generalSetting->headquarter }}</td>
                <td>{{ $generalSetting->linkedin_url }}</td>
                <td>{{ $generalSetting->facebook_url }}</td>
                <td>{{ $generalSetting->instagram_url }}</td>
                <td>{{ $generalSetting->youtube_url }}</td>

                <td width="120">
                    {!! Form::open(['route' => ['generalSettings.destroy', $generalSetting->id], 'method' => 'delete'])
                    !!}
                    <div class='btn-group'>
                        <a href="{{ route('generalSettings.show', [$generalSetting->id]) }}"
                            class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('generalSettings.edit', [$generalSetting->id]) }}"
                            class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn
                        btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>