routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/', App\Http\Controllers\FrontController::class)->name('front');

Auth::routes();

Route::apiResource('attachments', \App\Http\Controllers\AttachmentController::class)->only(['store', 'show', 'destroy']);

Route::group([ 'prefix' => 'admin', 'middleware' => 'auth' ], function() {

    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('admin');
    
    
    Route::resource('generalSettings', App\Http\Controllers\GeneralSettingController::class);
    
    
    Route::resource('myExpertises', App\Http\Controllers\MyExpertiseController::class);
    
    
    Route::resource('myExperiences', App\Http\Controllers\MyExperienceController::class);
    
    
    Route::resource('education', App\Http\Controllers\EducationController::class);
    
    
    Route::resource('skills', App\Http\Controllers\SkillController::class);
});




Route::resource('testimonials', App\Http\Controllers\TestimonialController::class);


Route::resource('portfolios', App\Http\Controllers\PortfolioController::class);

app/Models/MyExperience.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class MyExperience
 * @package App\Models
 * @version August 5, 2022, 2:05 am UTC
 *
 */
class MyExperience extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'my_experiences';
    

    protected $dates = [
        'deleted_at',
        'start_date',
        'end_date',
    ];



    public $fillable = [
        'name',
        'start_date',
        'end_date',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/MyExperienceController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateMyExperienceRequest;
use App\Http\Requests\UpdateMyExperienceRequest;
use App\Repositories\MyExperienceRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class MyExperienceController extends AppBaseController
{
    /** @var MyExperienceRepository $myExperienceRepository*/
    private $myExperienceRepository;

    public function __construct(MyExperienceRepository $myExperienceRepo)
    {
        $this->myExperienceRepository = $myExperienceRepo;
    }

    /**
     * Display a listing of the MyExperience.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $myExperiences = $this->myExperienceRepository->all();

        return view('my_experiences.index')
            ->with('myExperiences', $myExperiences);
    }

    /**
     * Show the form for creating a new MyExperience.
     *
     * @return Response
     */
    public function create()
    {
        return view('my_experiences.create');
    }

    /**
     * Store a newly created MyExperience in storage.
     *
     * @param CreateMyExperienceRequest $request
     *
     * @return Response
     */
    public function store(CreateMyExperienceRequest $request)
    {
        $input = $request->all();

        $myExperience = $this->myExperienceRepository->create($input);

        Flash::success('My Experience saved successfully.');

        return redirect(route('myExperiences.index'));
    }

    /**
     * Display the specified MyExperience.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $myExperience = $this->myExperienceRepository->find($id);

        if (empty($myExperience)) {
            Flash::error('My Experience not found');

            return redirect(route('myExperiences.index'));
        }

        return view('my_experiences.show')->with('myExperience', $myExperience);
    }

    /**
     * Show the form for editing the specified MyExperience.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $myExperience = $this->myExperienceRepository->find($id);

        if (empty($myExperience)) {
            Flash::error('My Experience not found');

            return redirect(route('myExperiences.index'));
        }

        return view('my_experiences.edit')->with('myExperience', $myExperience);
    }

    /**
     * Update the specified MyExperience in storage.
     *
     * @param int $id
     * @param UpdateMyExperienceRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateMyExperienceRequest $request)
    {
        $myExperience = $this->myExperienceRepository->find($id);

        if (empty($myExperience)) {
            Flash::error('My Experience not found');

            return redirect(route('myExperiences.index'));
        }

        $myExperience = $this->myExperienceRepository->update($request->all(), $id);

        Flash::success('My Experience updated successfully.');

        return redirect(route('myExperiences.index'));
    }

    /**
     * Remove the specified MyExperience from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $myExperience = $this->myExperienceRepository->find($id);

        if (empty($myExperience)) {
            Flash::error('My Experience not found');

            return redirect(route('myExperiences.index'));
        }

        $this->myExperienceRepository->delete($id);

        Flash::success('My Experience deleted successfully.');

        return redirect(route('myExperiences.index'));
    }
}

resources/views/my_experiences/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create My Experience</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'myExperiences.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('my_experiences.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('myExperiences.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/my_experiences/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit My Experience</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($myExperience, ['route' => ['myExperiences.update', $myExperience->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('my_experiences.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('myExperiences.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/my_experiences/fields.blade.php
<div class="col-md-12">
    <div class="form-group">
        {!! Form::label('name', 'Name*') !!}
        {!! Form::text(
        'name',
        null,
        [
        'class' => 'form-control ' . ($errors->has('name') ? 'is-invalid' : ''),
        'maxlength' => '50',
        'minlength' => '3',
        'required'
        ]
        ) !!}
        @error('name')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>
    <div class="form-group">
        {!! Form::label('start_date', 'Start Date*') !!}
        {!! Form::date(
        'start_date',
        null,
        [
        'class' => 'form-control ' . ($errors->has('start_date') ? 'is-invalid' : ''),
        'maxlength' => '50',
        'minlength' => '3',
        'required'
        ]
        ) !!}
        @error('start_date')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>
    <div class="form-group">
        {!! Form::label('end_date', 'End Date*') !!}
        {!! Form::date(
        'end_date',
        null,
        [
        'class' => 'form-control ' . ($errors->has('end_date') ? 'is-invalid' : ''),
        'maxlength' => '50',
        'minlength' => '3',
        'required'
        ]
        ) !!}
        @error('end_date')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>
</div>

resources/views/my_experiences/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>My Experiences</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('myExperiences.create') }}">
                        Add New
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('my_experiences.table')

                <div class="card-footer clearfix">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/my_experiences/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>My Experience Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('myExperiences.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('my_experiences.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/my_experiences/show_fields.blade.php
<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $myExperience->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $myExperience->updated_at }}</p>
</div>

resources/views/my_experiences/table.blade.php
<div class="table-responsive">
    <table class="table" id="myExperiences-table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach($myExperiences as $myExperience)
            <tr>
                <td>{{ $myExperience->name }}</td>
                <td>{{ $myExperience->start_date->format('d M Y') }}</td>
                <td>{{ $myExperience->end_date->format('d M Y') }}</td>
                <td width="120">
                    {!! Form::open(['route' => ['myExperiences.destroy', $myExperience->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('myExperiences.show', [$myExperience->id]) }}" class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('myExperiences.edit', [$myExperience->id]) }}" class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn
                        btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>